---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-Types-DateTime
no_index:
  directory:
    - t
    - inc
requires:
  DateTime: 0.4302
  DateTime::Duration: 0.4302
  DateTime::Locale: 0.4001
  DateTime::TimeZone: 0.95
  Moose: 0.41
  MooseX::Types: 0.30
  MooseX::Types::Moose: 0.30
  Test::Exception: 0.27
  Test::use::ok: 0.02
  namespace::clean: 0.08
resources:
  repository: git://git.moose.perl.org/MooseX-Types-DateTime.git
version: 0.07
